spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?stringtype=unspecified
    username: postgres
    password: 161657
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: application
